### ISSUE TITLE
AWS_PROFILE

### ISSUE THREAD

**Issue by gilcohen67** [Zira-integrations/deployment-template#1]
Tested out the Template, all works great, only thing I had to change was the AWS_PROFILE in mydeploy-prod.sh.
Is there any way that can pull directly from the default aws profile, or ask the user which profile? #2

**Comment by YuriyMorkovnik** [comment]
I put under comment `export AWS_PROFILE='integrations` so it will use your default aws profile

**Comment by YuriyMorkovnik** [comment]
so you will be able to use needed config by running export AWS_PROFILE='YOUR_CONFIG_NAME'
